POST http://localhost:8080/api/students
content-type: application/json

{
    "name": "Meet Chaudhary",
    "age": 20,
    "adhar": "123456789012",
    "university": "Chitkara"
}

###
POST http://localhost:8080/api/students
content-type: application/json

{
    "name": "John Snow",
    "age": 25,
    "adhar": "123456789013",
    "university": "LPU"
}

###
POST http://localhost:8080/api/students
content-type: application/json

{
    "name": "Dexter Morgan",
    "age": 30,
    "adhar": "123456789014",
    "university": "Chitkara"
}

###
POST http://localhost:8080/api/students
content-type: application/json

{
    "name": "Ted Mosby",
    "age": 35,
    "adhar": "123456789015",
    "university": "IITD"
}

### Get All Students
GET http://localhost:8080/api/students

###
GET http://localhost:8080/api/students/uni/Chitkara

###
GET http://localhost:8080/api/students/1